export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};
import HeaderDash from "../../../app/components/NavBarDash/NavDashDash";
import "../../globals.css";
export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <HeaderDash></HeaderDash>
        {children}
      </body>
    </html>
  );
}
